doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        mappings:
            App:
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity\'
